version: '3.4'

services:
  mongodb-insurance-policy:
    image: mongo:latest
    container_name: mongodb-insurance-policy
    hostname: mongodb-insurance-policy
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}  # Adicione essa variável se precisar de um banco de dados inicial
    networks:
      - insurance-policy
    ports:
      - "27017:27017"
    volumes:
      - "mongo-insurance-policy:/data/db"
      - "./migrations/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
    healthcheck:
      test: 'echo "db.runCommand({ ping: 1 })" | mongo --quiet'
      interval: 10s
      start_period: 30s

  insurance-policy-api:
    build: .
    container_name: insurance-policy-api
    restart: always
    ports:
      - "8080:8080"
    networks:
      - insurance-policy
      
volumes:
  mongo-insurance-policy:
    driver: local

networks: 
  insurance-policy:
    name: insurance-policy